title = "alleinsein aevum"
baseURL = 'https://alleinsein-aevum.netlify.app/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
enableEmoji = true

# theme = "hugo-blog-awesome"

[markup.highlight]
  noClasses = false

[Languages.zh-cn]
  languageName = "中文"
  languageCode = "zh-cn"
  contentDir = "content/zh"
  weight = 1

  [[Languages.zh-cn.menu.main]]
    name = '首页'
    url = '/'
    weight = 10
  [[Languages.zh-cn.menu.main]]
    name = '文章'
    url = '/posts/'
    weight = 20
  [[Languages.zh-cn.menu.main]]
    name = '关于'
    url = '/about/'
    weight = 30

[Languages.zh-cn.params]
  sitename = "alleinsein aevum"
  description = "赛博漫游者"
  defaultColor = "dark"
  mainSections = ['posts']

[Languages.zh-cn.params.author]
  name = "Audrey"
  intro = "alleinsein aevum"
  description = "赛博漫游者"
  avatar = "cyber-me.jpg" 
